version: '3.8'

services:
  api:
    build: .
    container_name: nest_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"
      WATCHPACK_POLLING: "true"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:docker

  mongodb:
    image: mongo:7
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
